### ISSUE TITLE
Problem with 1.4 update

### ISSUE THREAD

**Issue by gabak** [apppresser/AppPresser#14]
I just update to version 1.4, it is working good on mobile but display as mobile on desktop system, please what can i do to revert it back. thanks

**Comment by stillatmylinux** [comment]
The mobile theme sets a cookie AppPresser_Appp, AppPresser_Appp2 or AppPresser_Appp3 depending on what version you are using.  You can clear that cookie or open in an incognito window.    For version three, it will clear by itself in five minutes without having to clear the cookie manually.
