### ISSUE TITLE
Where is the save button in settings?

### ISSUE THREAD

**Issue by hderaps** [apppresser/AppPresser#15]
Getting a weird situation, you save button does not show up. see screenshot
![screenshot](https://user-images.githubusercontent.com/1489963/27947492-631e3e9c-6339-11e7-9f0e-b1ab376ef6a2.jpg)

Tried disabling all plugins and still did not work. Any ideas?

**Comment by stillatmylinux** [comment]
There may be a PHP error on the page causing it to truncate the page.  View the HTML source to see if that is the case.  Also, you may have turned on the debugging logger which may have grown too large making the page load very slowly.  If that is the case you can delete the log file. Find it in wp-content/uploads/apppresser/

If you have an active license you can ask us to take a closer look by using our contact page.  https://apppresser.com/contact/

**Comment by hderaps** [comment]
Hi Matt,

Thanks for the reply, will check it out and get back to you.

Yeah it's weird my production site is fine but my staging copy has the
problem.



Cheers

Hugh

Sent from my android mobile phone.

On 11 Jul. 2017 01:12, "Matt Thiessen" <notifications@github.com> wrote:

There may be a PHP error on the page causing it to truncate the page. View
the HTML source to see if that is the case. Also, you may have turned on
the debugging logger which may have grown too large making the page load
very slowly. If that is the case you can delete the log file. Find it in
wp-content/uploads/apppresser/

If you have an active license you can ask us to take a closer look by using
our contact page. https://apppresser.com/contact/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/apppresser/AppPresser/issues/15#issuecomment-314136670>,
or mute the thread
